stage: prd
env: {}
strapi:
  enabled: false
secrets:
  datDb:
    host: ""
    port: "3306"
    username: ""
    password: ""
    database: "dsearchtree"
gras-deploy:
  enabled: false
grases:
  gras:
    enabled: true
    gras: {}
    grapi:
      name: dat-demo
      runimages:
        image: grpl/loopback
        tag: "0.4.25"
      buildimages:
        enabled: true
        tag: 0.0.1
      deployimages:
        enabled: true
      discoveredrepos: true
      ingress: true
      ssl: true
      sslissuer: letsencrypt-grapple-demo
      autoscaling:
        maxReplicas: 3
      extraSecrets:
        - dat-db-config
        - dat-sqlcontrollers
      datasources:
        - name: dsearchtree
          spec:
            mysql:
              database: $(database)
              host: $(host)
              name: dsearchtree
              password: $(password)
              port: $(port)
              url: ""
              user: $(username)
      discoveries:
        - name: dsearchtree
          spec:
            all: true
            dataSource: dsearchtree
            disableCamelCase: false
            schema: $(database)
      restcruds:
        - name: dsearchtree
          spec:
            datasource: dsearchtree
      models: []
      repositories: []
      relations: []
      openapis: []
      cacheconfigs: []
      controllers: []
      postpatches: []
      services: []
      serviceproviders: []
      prerelationpatches: []
      prepatches: []
      prediscoverypatches: []
    gruim:
      name: dat-demo
      runimages:
        image: grpl/gruim
        tag: "0.3.61"
      buildimages:
        enabled: true
        tag: 0.0.1
      deployimages:
        enabled: true
      ssl: true
      sslissuer: letsencrypt-grapple-demo
      autoscaling:
        maxReplicas: 3
      style: '{"colors":{"primary":"#1451cb"}}'
      config: ""
      additionalpackages: ""
      custommodules: []
      prepatches: []
      postpatches: []
replicaCount: 1
image:
  repository: grpl/grpl-dat-demo
  pullPolicy: Always
  tag: "devspace"
imagetest:
  repository: grpl/grpl-dat-demo-test
  pullPolicy: Always
  tag: ""
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: true
  annotations: {}
  name: ""
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
service:
  type: ClusterIP
  port: 80
lookup:
  enabled: true
  productName: dat-demo
  domain: MYDOMAIN.grpl.io
  sslissuer: MYISSUER
ingress:
  enabled: true
  className: ""
  ssl: true
  annotations: {}
  hosts: []
  tls: []
resources: {}
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
nodeSelector: {}
tolerations: []
affinity: {}
